version: '3.8'

services:
  appflowy:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: appflowy
    restart: unless-stopped
    ports:
      - "6080:6080"  # noVNC web interface
    environment:
      - DISPLAY=:99
      - VNC_PORT=5900
      - NOVNC_PORT=6080
    volumes:
      # Persist user data
      - appflowy_data:/home/appflowy/.local/share/appflowy
      - appflowy_config:/home/appflowy/.config/appflowy
    networks:
      - appflowy_network
    labels:
      - "com.appflowy.description=AppFlowy - Open Source Alternative to Notion"
      - "com.appflowy.version=0.9.4"

volumes:
  appflowy_data:
    driver: local
  appflowy_config:
    driver: local

networks:
  appflowy_network:
    driver: bridge